### ISSUE TITLE
eccodes paths to be removed and positionned by vortex according to the executable

### ISSUE THREAD

**Issue by AlexandreMary** [ACCORD-NWP/DAVAI-tests#35]
ECCODES_SAMPLES_PATH and ECCODES_DEFINITION_PATH are specified in the config file

* the DEFINITION may not be necessary
* the SAMPLES has been added in CY49 to circumvent a necessary update of that path to `grib1_mlgrib2`
* these paths are positionned by vortex accordingly to the executable (via a sort of `ldd | grep libeccodes.so`) : it is there that the path should be changed, conditionnally to the cycle.
  An [Issue](http://gitlab.meteo.fr/cnrm-gmap/vortex/-/issues/3) has been open on this topic on Vortex Gitlab.

Note: blocking-point as it puts a constraint on the version of eccodes linked in epygram/FA and the model to be the same.

**Comment by tlestang** [comment]
Fixed in [vortex#12](http://gitlab.meteo.fr/cnrm-gmap/vortex/-/merge_requests/12)

**Comment by AlexandreMary** [comment]
Solved
