### ISSUE TITLE
optvcc missing from belenos.ini in DC49T0_to_T1

### ISSUE THREAD

**Issue by rolfhm** [ACCORD-NWP/DAVAI-tests#6]
`optvcc` is included in `atos_bologna.ini` 
https://github.com/ACCORD-NWP/DAVAI-tests/blob/a3c9a685c1696501771ce6562c20a7c17a62f79c/conf/atos_bologna.ini#L212
but not in `belenos.ini` in the CY49T0_to_T1 branch. This causes build to fail on Belenos , because `pack2bin` is looking for this option.
https://github.com/ACCORD-NWP/DAVAI-tests/blob/a3c9a685c1696501771ce6562c20a7c17a62f79c/src/tasks/build/gmkpack/pack2bin.py#L91-L92
Removing the option from from `pack2bin` lets me compile on Belenos.

**Comment by AlexandreMary** [comment]
Fixed with commit 67a2e3c8d04 of branch `DV49T0_to_T1`
